# Generated by Django 5.0.8 on 2024-08-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_arabic_faq_bundle_english_faq_advantage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='description',
        ),
    ]
