# Generated by Django 5.0.8 on 2024-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_bundle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
