# Generated by Django 5.0.8 on 2024-08-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_advantage_description_alter_bundle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advantage',
            old_name='description',
            new_name='advantage',
        ),
    ]
