# Generated by Django 5.0.8 on 2024-08-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_rename_description_advantage_advantage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
    ]
