# Generated by Django 5.0.8 on 2024-08-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EnglishFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Advantage',
            new_name='ArabicAdvantage',
        ),
        migrations.RenameModel(
            old_name='Bundle',
            new_name='ArabicBundle',
        ),
        migrations.RenameModel(
            old_name='Arabic_FAQ',
            new_name='ArabicFAQ',
        ),
        migrations.RenameModel(
            old_name='Footer',
            new_name='ArabicFooter',
        ),
        migrations.RenameModel(
            old_name='English_FAQ',
            new_name='EnglishFAQ',
        ),
        migrations.CreateModel(
            name='EnglishAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.CharField(max_length=500)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='portal.englishbundle')),
            ],
        ),
    ]
