# Generated by Django 5.0.8 on 2024-08-17 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_englishbundle_englishfooter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_advantage', models.CharField(max_length=500)),
                ('arabic_advantage', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_question', models.CharField(max_length=350)),
                ('english_asnwer', models.CharField(max_length=5000)),
                ('arabic_question', models.CharField(max_length=350)),
                ('arabic_asnwer', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_address', models.CharField(max_length=255)),
                ('arabic_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='arabicadvantage',
            name='bundle',
        ),
        migrations.DeleteModel(
            name='ArabicFAQ',
        ),
        migrations.DeleteModel(
            name='ArabicFooter',
        ),
        migrations.RemoveField(
            model_name='englishadvantage',
            name='bundle',
        ),
        migrations.DeleteModel(
            name='EnglishFAQ',
        ),
        migrations.DeleteModel(
            name='EnglishFooter',
        ),
        migrations.AddField(
            model_name='advantage',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='portal.bundle'),
        ),
        migrations.DeleteModel(
            name='ArabicAdvantage',
        ),
        migrations.DeleteModel(
            name='ArabicBundle',
        ),
        migrations.DeleteModel(
            name='EnglishAdvantage',
        ),
        migrations.DeleteModel(
            name='EnglishBundle',
        ),
    ]
