# Generated by Django 5.0.8 on 2024-08-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_advantage_bundle_faq_footer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='arabic_asnwer',
            new_name='arabic_answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='english_asnwer',
            new_name='english_answer',
        ),
    ]
