# Generated by Django 5.0.8 on 2024-09-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_title', models.CharField(max_length=255)),
                ('arabic_title', models.CharField(max_length=255)),
                ('english_description', models.TextField()),
                ('arabic_description', models.TextField()),
            ],
        ),
    ]
