# Generated by Django 5.2.8 on 2025-12-04 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_homestarting'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestarting',
            name='arabic_subtitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homestarting',
            name='english_subtitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
