# Generated by Django 5.2.8 on 2025-12-06 18:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_homestarting_arabic_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
