# Generated by Django 5.2.8 on 2025-12-06 18:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_aboutus_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='content2',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
