# Generated by Django 5.2.9 on 2025-12-15 01:23

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_aboutus_content2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('arabic_title', models.CharField(max_length=255)),
                ('english_title', models.CharField(max_length=400)),
                ('arabic_subtitle', models.CharField(max_length=400)),
                ('english_content', ckeditor.fields.RichTextField()),
                ('arabic_content', ckeditor.fields.RichTextField()),
                ('section_image', models.FileField(blank=True, null=True, upload_to='about_section', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webm'])])),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='content2',
        ),
    ]
