# Generated by Django 5.2.9 on 2025-12-15 01:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_aboutsection_remove_aboutus_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='arabic_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='english_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='english_subtitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='english_title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='AboutSectionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_advantage', models.CharField(max_length=500)),
                ('arabic_advantage', models.CharField(max_length=500)),
                ('aboutSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AboutSection', to='portal.aboutsection')),
            ],
        ),
    ]
