# Generated by Django 5.2.9 on 2025-12-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_aboutsection_arabic_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='arabic_subtitle',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='english_subtitle',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
