# Generated by Django 5.2.9 on 2025-12-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_alter_aboutsection_arabic_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_identifier', models.SlugField(help_text="Unique identifier for the page (e.g., 'home', 'about-us')", max_length=200, unique=True)),
                ('page_title', models.CharField(help_text='Page title displayed in browser tab and as main heading', max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title for search engines (50-60 characters)', max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (150-160 characters)', max_length=160, null=True)),
                ('page_url', models.URLField(blank=True, help_text='Canonical URL for this page', null=True)),
                ('language', models.CharField(blank=True, default='en', help_text='Page language (e.g., en, ar)', max_length=10)),
                ('notes', models.TextField(blank=True, help_text="Internal notes about this page's SEO", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO Metadata',
                'verbose_name_plural': 'Page SEO Metadata',
                'ordering': ['page_identifier'],
            },
        ),
        migrations.CreateModel(
            name='SEOMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text="Page type this meta tag belongs to (e.g., 'home', 'about')", max_length=50)),
                ('attribute_type', models.CharField(choices=[('name', 'Meta Name (name attribute)'), ('property', 'Meta Property (property attribute)')], help_text="Choose between 'name' or 'property' attribute", max_length=10)),
                ('meta_name', models.CharField(help_text="Meta tag name (e.g., 'description', 'og:title', 'twitter:card')", max_length=255)),
                ('meta_content', models.TextField(help_text='Meta tag content/value')),
                ('meta_description', models.CharField(blank=True, help_text='Description of what this meta tag does (for admin reference)', max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order of display')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this meta tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Meta Tag',
                'verbose_name_plural': 'SEO Meta Tags',
                'ordering': ['content_type', 'order', 'meta_name'],
                'unique_together': {('content_type', 'attribute_type', 'meta_name')},
            },
        ),
    ]
