# Generated by Django 5.2.9 on 2025-12-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_metadata_metatag_delete_pageseometadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatag',
            name='content_type',
        ),
        migrations.AddField(
            model_name='metatag',
            name='attribute_type',
            field=models.CharField(choices=[('name', 'Name'), ('property', 'Property')], default='name', help_text="Choose between 'name' or 'property' attribute", max_length=10),
        ),
    ]
