# Generated by Django 5.2.9 on 2025-12-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_remove_metatag_content_type_metatag_attribute_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsectionlist',
            name='aboutSection',
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.RemoveField(
            model_name='advantage',
            name='bundle',
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='AboutSectionList',
        ),
        migrations.DeleteModel(
            name='Advantage',
        ),
        migrations.DeleteModel(
            name='Bundle',
        ),
    ]
