# Generated by Django 5.2.9 on 2025-12-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_remove_aboutsectionlist_aboutsection_delete_aboutus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
