# Generated by Django 5.2.9 on 2025-12-31 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_new_image_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAndPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='customers_and_partners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webm'])])),
                ('image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_title', models.CharField(max_length=255)),
                ('arabic_title', models.CharField(max_length=255)),
                ('english_description', models.TextField()),
                ('arabic_description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='who_we_are/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webm'])])),
                ('image_alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homestarting',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='home_starting/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webm'])]),
        ),
        migrations.AddField(
            model_name='homestarting',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
