# Generated by Django 5.2.9 on 2025-12-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_customerandpartner_whoweare_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='role',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
