# Generated by Django 5.2.9 on 2025-12-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_systempartner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systempartner',
            options={},
        ),
        migrations.RemoveField(
            model_name='systempartner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='systempartner',
            name='order',
        ),
    ]
