# Generated by Django 5.2.9 on 2025-12-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='job_title',
            new_name='arabic_job_title',
        ),
        migrations.AddField(
            model_name='comment',
            name='english_job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
