# Generated by Django 5.2.9 on 2025-12-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_rename_job_title_comment_arabic_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
