# Generated by Django 5.2.9 on 2025-12-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(),
        ),
    ]
