# Generated by Django 5.2.9 on 2026-01-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_footer_facebook_url_footer_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
