# Generated by Django 5.2.9 on 2026-01-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_footer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerandpartner',
            old_name='image_alt_text',
            new_name='arabic_alt',
        ),
        migrations.RenameField(
            model_name='homestarting',
            old_name='image_alt_text',
            new_name='arabic_alt',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='image_alt_text',
            new_name='arabic_alt',
        ),
        migrations.RenameField(
            model_name='systempartner',
            old_name='logo_alt_text',
            new_name='arabic_alt',
        ),
        migrations.RenameField(
            model_name='whoweare',
            old_name='image_alt_text',
            new_name='arabic_alt',
        ),
        migrations.AddField(
            model_name='customerandpartner',
            name='english_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homestarting',
            name='english_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='english_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systempartner',
            name='english_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='english_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
