# Generated by Django 5.2.9 on 2026-01-12 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_remove_metadata_page_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='english_page_title_for_metadata',
            field=models.CharField(default=django.utils.timezone.now, help_text='Page title displayed in browser tab and as main heading', max_length=255),
            preserve_default=False,
        ),
    ]
