# Generated by Django 5.2.9 on 2026-01-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_alter_metadata_english_page_title_for_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='english_page_title_for_metadata',
            field=models.CharField(default='Prokeys', help_text='Page title displayed in browser tab and as main heading', max_length=255),
        ),
    ]
