# Generated by Django 5.2.9 on 2026-03-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_alter_metadata_english_page_title_for_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('about', 'About page'), ('faq', 'FAQ page'), ('bundles', 'Bundles page'), ('services', 'Services page'), ('contact', 'Contact page'), ('blogs', 'Blogs page')], help_text="Logical page key used by the frontend (e.g. 'about').", max_length=50, unique=True)),
                ('english_path', models.SlugField(allow_unicode=True, blank=True, help_text="Optional English URL path segment, e.g. 'AboutUs'. If empty, frontend default is used.", max_length=255, null=True)),
                ('arabic_path', models.SlugField(allow_unicode=True, blank=True, help_text='Optional Arabic URL path segment. If empty, frontend default is used.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Page path',
                'verbose_name_plural': 'Page paths',
            },
        ),
    ]
