# Generated by Django 5.2.9 on 2026-01-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='page_title',
        ),
        migrations.AddField(
            model_name='metadata',
            name='arabic_page_description_for_metadata',
            field=models.TextField(blank=True, help_text='Meta description for SEO purposes', null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='arabic_page_title_for_metadata',
            field=models.CharField(blank=True, help_text='Page title displayed in browser tab and as main heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='english_page_description_for_metadata',
            field=models.TextField(blank=True, help_text='Meta description for SEO purposes', null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='english_page_title_for_metadata',
            field=models.CharField(blank=True, help_text='Page title displayed in browser tab and as main heading', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='MetaTag',
        ),
    ]
