# Generated by Django 5.2.9 on 2025-12-27 14:25

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_title', models.CharField(max_length=255)),
                ('arabic_title', models.CharField(max_length=255)),
                ('english_description', models.TextField()),
                ('arabic_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_sections/')),
                ('english_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('arabic_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image_position', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('top', 'Top'), ('bottom', 'Bottom')], default='left', max_length=6)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='services.service')),
            ],
        ),
    ]
