# Generated by Django 5.2.9 on 2025-12-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicespagemetadata_servicespagemetatag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesection',
            name='image_position',
        ),
        migrations.AddField(
            model_name='servicesection',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
