# Generated by Django 5.2.9 on 2026-01-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_servicesection_image_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesDescriptionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_title', models.CharField(default='Our Services', max_length=255)),
                ('arabic_title', models.CharField(default='خدماتنا', max_length=255)),
                ('english_description', models.TextField()),
                ('arabic_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image_alt_text', models.CharField(blank=True, default='Professional', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Description Sections',
            },
        ),
    ]
