# Generated by Django 5.2.9 on 2026-01-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicesdescriptionsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesection',
            old_name='image_alt_text',
            new_name='arabic_alt',
        ),
        migrations.RemoveField(
            model_name='servicesdescriptionsection',
            name='image_alt_text',
        ),
        migrations.AddField(
            model_name='servicesdescriptionsection',
            name='arabic_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicesdescriptionsection',
            name='english_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='english_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
