# Generated by Django 5.2.9 on 2026-01-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_image_alt_text_servicesection_arabic_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespagemetatag',
            name='attribute_type',
            field=models.CharField(choices=[('name', 'Name')], default='name', help_text="Choose between 'name' or 'property' attribute", max_length=10),
        ),
        migrations.AlterField(
            model_name='servicespagemetatag',
            name='meta_name',
            field=models.CharField(default='description', help_text="Meta tag name (e.g., 'description', 'og:title', 'twitter:card')", max_length=255),
        ),
        migrations.AlterField(
            model_name='singleservicemetatag',
            name='attribute_type',
            field=models.CharField(choices=[('name', 'Name')], default='name', help_text="Choose between 'name' or 'property' attribute", max_length=10),
        ),
        migrations.AlterField(
            model_name='singleservicemetatag',
            name='meta_name',
            field=models.CharField(default='description', help_text="Meta tag name (e.g., 'description', 'og:title', 'twitter:card')", max_length=255),
        ),
    ]
