# Generated by Django 5.2.9 on 2026-01-12 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicespagemetatag_attribute_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleservicemetadata',
            name='service',
        ),
        migrations.RemoveField(
            model_name='singleservicemetatag',
            name='page',
        ),
        migrations.RenameField(
            model_name='servicespagemetadata',
            old_name='page_title',
            new_name='arabic_page_title_for_metadata',
        ),
        migrations.AddField(
            model_name='service',
            name='arabic_page_description_for_metadata',
            field=models.TextField(blank=True, help_text='Meta description for SEO purposes', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='arabic_page_title_for_metadata',
            field=models.CharField(default=django.utils.timezone.now, help_text='Page title displayed in browser tab and as main heading', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='english_page_description_for_metadata',
            field=models.TextField(blank=True, help_text='Meta description for SEO purposes', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='english_page_title_for_metadata',
            field=models.CharField(default=django.utils.timezone.now, help_text='Page title displayed in browser tab and as main heading', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicespagemetadata',
            name='arabic_page_description_for_metadata',
            field=models.TextField(blank=True, help_text='Meta description for SEO purposes', null=True),
        ),
        migrations.AddField(
            model_name='servicespagemetadata',
            name='english_page_description_for_metadata',
            field=models.TextField(blank=True, help_text='Meta description for SEO purposes', null=True),
        ),
        migrations.AddField(
            model_name='servicespagemetadata',
            name='english_page_title_for_metadata',
            field=models.CharField(default=django.utils.timezone.now, help_text='Page title displayed in browser tab and as main heading', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServicesPageMetaTag',
        ),
        migrations.DeleteModel(
            name='SingleServiceMetadata',
        ),
        migrations.DeleteModel(
            name='SingleServiceMetaTag',
        ),
    ]
