# Generated by Django 5.2.9 on 2026-01-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_singleservicemetadata_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='arabic_page_title_for_metadata',
            field=models.CharField(blank=True, help_text='Page title displayed in browser tab and as main heading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='english_page_title_for_metadata',
            field=models.CharField(blank=True, help_text='Page title displayed in browser tab and as main heading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicespagemetadata',
            name='arabic_page_title_for_metadata',
            field=models.CharField(blank=True, help_text='Page title displayed in browser tab and as main heading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicespagemetadata',
            name='english_page_title_for_metadata',
            field=models.CharField(blank=True, help_text='Page title displayed in browser tab and as main heading', max_length=255, null=True),
        ),
    ]
