# Generated by Django 5.2.9 on 2026-01-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_arabic_page_title_for_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespagemetadata',
            name='english_page_title_for_metadata',
            field=models.CharField(default='Services', help_text='Page title displayed in browser tab and as main heading', max_length=255),
        ),
    ]
