# Generated by Django 5.2.9 on 2026-03-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicespagemetadata_english_page_title_for_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='arabic_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='english_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
