# Generated by Django 5.2.9 on 2026-03-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_arabic_slug_service_english_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='arabic_slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='english_slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
    ]
