# Generated by Django 5.2.9 on 2025-12-20 16:20

import blog.models
import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_title', models.CharField(max_length=255)),
                ('arabic_title', models.CharField(max_length=255)),
                ('english_description', models.TextField()),
                ('arabic_description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=blog.models.attachment, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webm'])])),
                ('english_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('arabic_content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
