# Generated by Django 5.2.9 on 2026-01-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogspagemetadata_blog_image_alt_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image_alt_text',
            new_name='arabic_alt',
        ),
        migrations.AddField(
            model_name='blog',
            name='english_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
