# Generated by Django 5.2.9 on 2026-01-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogspagemetatag_attribute_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signgleblogmetadata',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='singleblogmetatag',
            name='page',
        ),
        migrations.AddField(
            model_name='blog',
            name='page_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO purposes', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='page_title',
            field=models.CharField(blank=True, help_text='Page title for SEO purposes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogspagemetadata',
            name='page_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO purposes', null=True),
        ),
        migrations.DeleteModel(
            name='BlogsPageMetaTag',
        ),
        migrations.DeleteModel(
            name='SigngleBlogMetadata',
        ),
        migrations.DeleteModel(
            name='SingleBlogMetaTag',
        ),
    ]
