# Generated by Django 5.2.9 on 2026-01-12 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_signgleblogmetadata_blog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='page_description',
            new_name='arabic_page_description_for_metadata',
        ),
        migrations.RenameField(
            model_name='blogspagemetadata',
            old_name='page_description',
            new_name='arabic_page_description_for_metadata',
        ),
        migrations.RenameField(
            model_name='blogspagemetadata',
            old_name='page_title',
            new_name='arabic_page_title_for_metadata',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='page_title',
        ),
        migrations.AddField(
            model_name='blog',
            name='arabic_page_title_for_metadata',
            field=models.CharField(default=django.utils.timezone.now, help_text='Page title displayed in browser tab and as main heading', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='english_page_description_for_metadata',
            field=models.TextField(blank=True, help_text='Meta description for SEO purposes', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='english_page_title_for_metadata',
            field=models.CharField(default=django.utils.timezone.now, help_text='Page title displayed in browser tab and as main heading', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogspagemetadata',
            name='english_page_description_for_metadata',
            field=models.TextField(blank=True, help_text='Meta description for SEO purposes', null=True),
        ),
        migrations.AddField(
            model_name='blogspagemetadata',
            name='english_page_title_for_metadata',
            field=models.CharField(default=django.utils.timezone.now, help_text='Page title displayed in browser tab and as main heading', max_length=255),
            preserve_default=False,
        ),
    ]
