# Generated by Django 5.2.9 on 2026-01-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_page_description_blog_arabic_page_description_for_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='arabic_page_title_for_metadata',
            field=models.CharField(blank=True, help_text='Page title displayed in browser tab and as main heading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='english_page_title_for_metadata',
            field=models.CharField(blank=True, help_text='Page title displayed in browser tab and as main heading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogspagemetadata',
            name='arabic_page_title_for_metadata',
            field=models.CharField(blank=True, help_text='Page title displayed in browser tab and as main heading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogspagemetadata',
            name='english_page_title_for_metadata',
            field=models.CharField(blank=True, help_text='Page title displayed in browser tab and as main heading', max_length=255, null=True),
        ),
    ]
