# Generated by Django 5.2.9 on 2026-03-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_arabic_slug_blog_english_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='arabic_slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='english_slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
    ]
