# Generated by Django 5.0.8 on 2024-08-17 19:08

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_tax_record_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tax_record',
            field=models.ImageField(blank=True, upload_to='tax_records/', validators=[authentication.models.validate_image]),
        ),
    ]
