# Generated by Django 5.0.8 on 2024-08-18 09:26

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tax_record',
            field=models.ImageField(blank=True, null=True, upload_to='tax_records/', validators=[authentication.models.validate_image]),
        ),
    ]
