# Generated by Django 5.2.9 on 2025-12-31 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(help_text='Page title displayed in browser tab and as main heading', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_advantage', models.CharField(max_length=500)),
                ('arabic_advantage', models.CharField(max_length=500)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='bundles.bundle')),
            ],
        ),
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_type', models.CharField(choices=[('name', 'Name'), ('property', 'Property')], default='name', help_text="Choose between 'name' or 'property' attribute", max_length=10)),
                ('meta_name', models.CharField(help_text="Meta tag name (e.g., 'description', 'og:title', 'twitter:card')", max_length=255)),
                ('meta_content', models.TextField(help_text='Meta tag content/value')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_tags', to='bundles.metadata')),
            ],
        ),
    ]
