# Generated by Django 5.2.9 on 2025-12-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
