# Generated by Django 5.2.9 on 2025-12-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0002_bundle_discount_bundle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
