# Generated by Django 5.2.9 on 2025-12-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0003_bundle_best_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
