# Generated by Django 5.2.9 on 2026-01-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0005_descriptionsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionsection',
            name='image_alt_text',
        ),
        migrations.AddField(
            model_name='descriptionsection',
            name='arabic_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='descriptionsection',
            name='english_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
