# Generated by Django 5.2.9 on 2025-12-31 00:14

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('arabic_title', models.CharField(max_length=255)),
                ('english_title', models.CharField(max_length=255)),
                ('arabic_subtitle', models.CharField(blank=True, max_length=400, null=True)),
                ('english_subtitle', models.CharField(blank=True, max_length=400, null=True)),
                ('arabic_description', models.TextField()),
                ('english_description', models.TextField()),
                ('english_content', ckeditor.fields.RichTextField()),
                ('arabic_content', ckeditor.fields.RichTextField()),
                ('section_image', models.FileField(blank=True, null=True, upload_to='about_section', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webm'])])),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_title', models.CharField(max_length=255)),
                ('arabic_title', models.CharField(max_length=255)),
                ('english_description', models.TextField()),
                ('arabic_description', models.TextField()),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(help_text='Page title displayed in browser tab and as main heading', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSectionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_advantage', models.CharField(max_length=500)),
                ('arabic_advantage', models.CharField(max_length=500)),
                ('aboutSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AboutSection', to='about.aboutsection')),
            ],
        ),
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_type', models.CharField(choices=[('name', 'Name'), ('property', 'Property')], default='name', help_text="Choose between 'name' or 'property' attribute", max_length=10)),
                ('meta_name', models.CharField(help_text="Meta tag name (e.g., 'description', 'og:title', 'twitter:card')", max_length=255)),
                ('meta_content', models.TextField(help_text='Meta tag content/value')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_tags', to='about.metadata')),
            ],
        ),
    ]
