# Generated by Django 5.2.9 on 2025-12-31 00:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='arabic_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='english_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
