# Generated by Django 5.2.9 on 2025-12-31 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutsection_image_alt_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='content',
        ),
    ]
