# Generated by Django 5.2.9 on 2025-12-31 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_aboutus_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='arabic_description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='arabic_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='english_description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='english_subtitle',
        ),
        migrations.DeleteModel(
            name='AboutSectionList',
        ),
    ]
