# Generated by Django 5.2.9 on 2026-01-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_aboutsection_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsection',
            old_name='image_alt_text',
            new_name='arabic_alt',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='english_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
