# Generated by Django 5.2.9 on 2026-01-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_metadata_page_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='english_page_title_for_metadata',
            field=models.CharField(default='About Us', help_text='Page title displayed in browser tab and as main heading', max_length=255),
        ),
    ]
